development:
  sessions:
    default:
      database: curso-rails
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: CursoRails
      username: vitor
      password: vitor
      hosts:
        - dharma.mongohq.com:10036