development:
   sessions:
    default:
      database: CursoRails
      username: vitor
      password: vitor
      hosts:
        - dharma.mongohq.com:10036
production:
  sessions:
    default:
      database: CursoRails
      username: vitor
      password: vitor
      hosts:
        - dharma.mongohq.com:10036